AWSTemplateFormatVersion: 2010-09-09
Description: |
    This template will create Application Load Balancer with ASG using LT. This is a Milliseconds Converter
  Application aims to convert the given time in milliseconds into hours, minutes, and seconds. The application
  is to be coded in Python and deployed as a web application with Flask on AWS Application Load Balancer
  with Auto Scaling Group of Elastic Compute Cloud (EC2) Instances using AWS Cloudformation Service.
Parameters:
  
Metadata:
  
Mappings:
  
Conditions:
  
Resources:
  
Transform:
  
Outputs: